language: go
install: go get -u -v github.com/spf13/hugo
script:
  - hugo -t=casper
  - python --version
  - sudo -H pip install s3cmd
  - s3cmd sync --delete-removed -P -M -r public/ s3://solaegis.com/
notifications:
    email:
        on_failure: always
